### ISSUE TITLE
by_common for providers w/out common names

### ISSUE THREAD

**Issue by karinorman** [cboettig/taxadb#49]
`by_common` should return a meaningful error for providers that don't have common names. Providers w/common names should be listed in the function documentation (itis, col, gbif, ncbi, fb, slb iucn).

**Comment by cboettig** [comment]
@karinorman Ok, this is now fixed in `master`.  Currently I just have it throw a warning message and returns NULL 

(I'm always hesitant to throw errors when something might naturally be represented just as missing data, e.g. so the user doesn't have to do custom error handling if this is part of a script getting common names for all providers, for instance.  But I could be talked into using an error instead of warning here, so just re-open if necessary).
